### ISSUE TITLE
Dockerizar o banco de dados postgreSQL

### ISSUE THREAD

**Issue by caio-venancio** [unb-mds/2024-2-Squad04#1]
Precisamos de uma configuração padronizada para o banco de dados do projeto, facilitando o setup e garantindo consistência entre os ambientes de desenvolvimento. A solução deve permitir que o banco seja configurado e executado rapidamente usando Docker, eliminando dependências manuais e problemas de configuração local.

**Comment by EnzoEmir** [comment]
Comentário de fechamento:

Dockerização do banco de dados concluída .

Variáveis de ambiente: Configuradas via .env.
