### ISSUE TITLE
feat(src): Integrar o banco de dados com a aplicação

### ISSUE THREAD

**Issue by caio-venancio** [unb-mds/2024-2-Squad04#3]
# Integrar o banco de dados
Descrição

Escopo
Esta tarefa está relacionada ao back-end.

Tópicos para conclusão da tarefa:
- [ ] função de Create passa dados no banco de dados
- [ ] função de  Read ler no banco de dados
- [ ] função de Update modifica no banco de dados
- [ ] função de Delete deleta dado no banco de dados

**Comment by JMPNascimento** [comment]
Issue completada com commit na branch CRUD. Devido a um pequeno erro de código, nem todos os models estavam habilitados para o CRUD, agora estão. Principal funcionalidade do commit acabou sendo um refactoring então.
