### ISSUE TITLE
docs (docs): documentar arquitetura

### ISSUE THREAD

**Issue by EnzoEmir** [unb-mds/2024-2-Squad04#4]
---
# Documentar a Arquitetura do Software

## **Descrição**
Para melhorar a manutenção, escalabilidade e entendimento do sistema, é necessário documentar a arquitetura do software. Atualmente, a falta de uma documentação detalhada pode dificultar a colaboração entre desenvolvedores e a expansão do sistema. A documentação deve conter informações sobre os principais componentes, suas responsabilidades, e como eles interagem entre si.
<br>

## **Escopo**
Esta tarefa abrange o projeto como um todo e foca na criação de um documento abrangente sobre a arquitetura do software.
<br>

## **Tópicos para conclusão da tarefa**
- [x] Criar uma descrição detalhada da arquitetura geral do sistema, incluindo diagramas.
- [x] Documentar os principais componentes e seus papéis:
  - [x] **Front-end**
  - [x] **Back-end**
  - [x] **Banco de dados**
  - [x] **Serviços externos ou integrações**
- [x] Descrever o fluxo de dados e interações entre os componentes.

---

**Comment by VictorPontual** [comment]
arquivo explicando a arquitetura, levando em conta os pontos exigidos, feito com sucesso
